import random

question_data = [
  {"text": "The human body has 206 bones.", "answer": "True"},
  {"text": "Water boils at 100 degrees Celsius at sea level.", "answer": "True"},
  {"text": "The Sun is a planet.", "answer": "False"},
  {"text": "Albert Einstein developed the theory of relativity.", "answer": "True"},
  {"text": "Light travels faster than sound.", "answer": "True"},
  {"text": "The Earth is the center of the universe.", "answer": "False"},
  {"text": "Photosynthesis occurs in animal cells.", "answer": "False"},
  {"text": "Humans have walked on Mars.", "answer": "False"},
  {"text": "Mount Everest is the tallest mountain in the world.", "answer": "True"},
  {"text": "Venus is the closest planet to the Sun.", "answer": "False"},
  {"text": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True"},
  {"text": "The chemical symbol for gold is Au.", "answer": "True"},
  {"text": "Oxygen makes up most of the Earth's atmosphere.", "answer": "False"},
  {"text": "The speed of light is approximately 300,000 km/s.", "answer": "True"},
  {"text": "Whales are fish.", "answer": "False"},
  {"text": "Sound can travel through a vacuum.", "answer": "False"},
  {"text": "Neil Armstrong was the first man to walk on the Moon.", "answer": "True"},
  {"text": "A leap year has 366 days.", "answer": "True"},
  {"text": "The capital of France is Berlin.", "answer": "False"},
  {"text": "The Statue of Liberty was a gift from France to the USA.", "answer": "True"},
  {"text": "Water is made up of two hydrogen atoms and one oxygen atom.", "answer": "True"},
  {"text": "Tennis is played with a round ball.", "answer": "True"},
  {"text": "Basketball was invented in Canada.", "answer": "False"},
  {"text": "Cricket is played with a bat and a ball.", "answer": "True"},
  {"text": "The Olympic Games are held every 2 years.", "answer": "False"},
  {"text": "Lionel Messi is known for playing football.", "answer": "True"},
  {"text": "The FIFA World Cup is held every 6 years.", "answer": "False"},
  {"text": "Michael Phelps is an Olympic swimmer.", "answer": "True"},
  {"text": "Roger Federer is a famous football player.", "answer": "False"},
  {"text": "Chess is recognized as a sport.", "answer": "True"},
  {"text": "Humans can breathe in space without any equipment.", "answer": "False"},
  {"text": "The Moon reflects the Sun's light.", "answer": "True"},
  {"text": "Earth has two moons.", "answer": "False"},
  {"text": "Electric current is measured in amperes.", "answer": "True"},
  {"text": "The boiling point of water decreases at higher altitudes.", "answer": "True"},
  {"text": "Gravity only exists on Earth.", "answer": "False"},
  {"text": "Sound travels faster in water than in air.", "answer": "True"},
  {"text": "Dinosaurs and humans lived at the same time.", "answer": "False"},
  {"text": "The chemical formula for table salt is NaCl.", "answer": "True"},
  {"text": "The internet was invented in the 1800s.", "answer": "False"},
  {"text": "Sharks are mammals.", "answer": "False"},
  {"text": "There are 12 players on a soccer team.", "answer": "False"},
  {"text": "Basketball is played on a rectangular court.", "answer": "True"},
  {"text": "Volleyball is played with a bat.", "answer": "False"},
  {"text": "The Tokyo Olympics were held in 2021.", "answer": "True"},
  {"text": "India has won the Cricket World Cup twice.", "answer": "True"},
  {"text": "Tigers are herbivores.", "answer": "False"},
  {"text": "Penguins can fly.", "answer": "False"},
  {"text": "The heart pumps blood through the body.", "answer": "True"},
  {"text": "Mitochondria are found in plant and animal cells.", "answer": "True"},
  {"text": "The Amazon is the longest river in the world.", "answer": "False"},
  {"text": "A triangle has four sides.", "answer": "False"},
  {"text": "Pi is approximately equal to 3.14.", "answer": "True"},
  {"text": "The human brain is the largest organ in the body.", "answer": "False"},
  {"text": "All snakes are venomous.", "answer": "False"},
  {"text": "The Great Wall of China was built over centuries.", "answer": "True"},
  {"text": "There are 24 hours in a day.", "answer": "True"},
  {"text": "Light bulbs use electricity.", "answer": "True"},
  {"text": "An octopus has eight arms.", "answer": "True"},
  {"text": "Jupiter is the smallest planet in the solar system.", "answer": "False"},
  {"text": "The Eiffel Tower is in Rome.", "answer": "False"},
  {"text": "Plants take in carbon dioxide during photosynthesis.", "answer": "True"},
  {"text": "Saturn has rings.", "answer": "True"},
  {"text": "The Sahara is the largest desert in the world.", "answer": "True"},
  {"text": "Bats are blind.", "answer": "False"},
  {"text": "Diamonds are made of carbon.", "answer": "True"},
  {"text": "Honey never spoils.", "answer": "True"},
  {"text": "Humans have 5 senses.", "answer": "True"},
  {"text": "A heptagon has 8 sides.", "answer": "False"},
  {"text": "The first computer programmer was a woman.", "answer": "True"},
  {"text": "Australia is both a country and a continent.", "answer": "True"},
  {"text": "Sound travels in straight lines.", "answer": "True"},
  {"text": "Spiders are insects.", "answer": "False"},
  {"text": "Water is an element.", "answer": "False"},
  {"text": "Einstein won the Nobel Prize for his theory of relativity.", "answer": "False"},
  {"text": "The North Pole is in Antarctica.", "answer": "False"},
  {"text": "Birds are warm-blooded.", "answer": "True"},
  {"text": "The lungs are part of the digestive system.", "answer": "False"},
  {"text": "Magnetism is a force.", "answer": "True"},
  {"text": "Iron is a non-metal.", "answer": "False"},
  {"text": "Lightning is hotter than the surface of the sun.", "answer": "True"},
  {"text": "DNA stands for Deoxyribonucleic Acid.", "answer": "True"},
  {"text": "The pancreas produces insulin.", "answer": "True"},
  {"text": "The keyboard was invented before the typewriter.", "answer": "False"},
  {"text": "Olympic gold medals are made entirely of gold.", "answer": "False"},
  {"text": "A giraffe's neck has more bones than a human's.", "answer": "False"},
  {"text": "The speed of sound is faster than the speed of light.", "answer": "False"},
  {"text": "An astronaut's suit is white.", "answer": "True"},
  {"text": "The Atlantic Ocean is saltwater.", "answer": "True"},
  {"text": "Humans evolved from chimpanzees.", "answer": "False"},
  {"text": "Basketball was invented by James Naismith.", "answer": "True"},
  {"text": "Snakes have legs.", "answer": "False"},
  {"text": "The liver helps to filter toxins in the body.", "answer": "True"},
  {"text": "Atoms are the smallest particles in the universe.", "answer": "False"},
  {"text": "The color of the sky is always blue.", "answer": "False"},
  {"text": "The currency of Japan is the Yen.", "answer": "True"},
  {"text": "India is located in the Northern Hemisphere.", "answer": "True"},
  {"text": "Frogs are reptiles.", "answer": "False"},
  {"text": "Bees make honey.", "answer": "True"},
  {"text": "The Earth rotates from west to east.", "answer": "True"}
]
random.shuffle(question_data)
